Ejercicios de la clase 2 - Sara Cruz B.
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed6 pull request #16
Opened 2021-02-01 20:56 UTC by saracrz

Ejercicios del día dos resueltos.

2021-02-05 17:53 UTC, totegsito requested changes
¡Muy buen trabajo Sara! Un código super limpio 😄 

En el de la planta, tienes un detallito sólo por arreglar 👏

2021-02-05 17:53 UTC, totegsito commented on alumnos/clase2/ejercicios-dia-2-scb.js
> +    dias += 1;
Casi lo tienes! 😬  Estás contando dos veces los días, este `dias += 1;` hace que el resultado te esté dando 2 en vez de 1

2021-02-07 10:05 UTC, saracrz commented on alumnos/clase2/ejercicios-dia-2-scb.js
> +    dias += 1;
Ok! le echo un vistacillo!

2021-02-12 13:10 UTC, saracrz commented on alumnos/clase2/ejercicios-dia-2-scb.js
> +    dias += 1;
He hecho el cambio y está listo para revisar otra vez @totegsito

2021-02-20 11:12 UTC, totegsito approved these changes
Genial Sara! 👏

2021-02-20 11:12 UTC, totegsito commented on alumnos/clase2/ejercicios-dia-2-scb.js
> +    dias += 0;
En este caso, es mejor no sumar!

hacer un += 0 es igual a no poner ninguna suma 😬

2021-02-20 11:12 UTC, merged