Ejercicios clase 3
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed6 pull request #24
Opened 2021-02-07 09:41 UTC by saracrz

Ejercicios de la clase 3 :)

2021-02-07 22:28 UTC, totegsito requested changes
Gran trabajo Sara! 

Te he puesto un par de comentarios, échales un ojo y ya lo tendrías 💃

2021-02-07 22:28 UTC, totegsito commented on alumnos/scb/ejercicios-clase-3-scb.js
> +  }
Sólo te faltan los casos que dijimos en clase, 11, 12 y 13 😬

2021-02-07 22:28 UTC, totegsito commented on alumnos/scb/ejercicios-clase-3-scb.js
> +  return result.repeat(n)
Aquí con usar `str` en vez de `result` ya lo tendrías 😅

2021-02-12 13:46 UTC, saracrz commented on alumnos/scb/ejercicios-clase-3-scb.js
> +  return result.repeat(n)
listo!

2021-02-12 13:47 UTC, saracrz commented on alumnos/scb/ejercicios-clase-3-scb.js
> +  }
Hecho!

2021-02-22 20:08 UTC, totegsito approved these changes
Perfecto! 👏 👏

2021-02-22 21:00 UTC, merged